-> pandas dataframes is a table of columns and rows we can use to filter and perform operations.
-> it is a group of pandas series object that share the same index.
-> pd.DataFrame(data=mydata,index=myindex,columns=mycolumns) used to create a dataframe with the specified index and columns.
-> pd.read_csv() is used to read csv files we can also read many other file formats.
-> Here the columns are called features and the value or instance is called datapoint.
-> .info() is used to get the list of columns with their datatypes, memory use for the dataframe, number of missing values.
-> .columns, .index is used to get the columns and index for the dataframe.
-> .head(), .tail() is used to get the first or last five records in the dataframe which can be adjusted.
-> .describe() is used to get the common statistics like mean, median, mode, std, quartiles etc.. for each column.
-> .transpose() is used to get the transposed dataframe.
-> We can get multiple coloumns to display by giving the list of columns as a index.
-> We can drop the columns or rows using the df.drop(column_name,axis) here by default the axis is 0.
-> We can remember the axis is row or column by this analogy like we can think of shape in that the first tuple is rows and second is columns.
-> We can create a column by simply calling the column in as a index and assigning a value to it.
-> .set_index(index_name) can be used to set index of the dataframe. we can give multiple indexs.
-> .reset_index() is used to reset back to range based index and the current indexes will become into columns.
-> indexing in the dataframes can be done through below
    $ .iloc[index_val] can be used to get the row if the specific index of the dataframe is integer or not.
    $ .loc[index_str] can be used to get the row when a index of the dataframe is string value.
-> Conditions in the dataframes can be used in directly by using the conditional operators and givin the result as a index for the dataframe.
    $ Chaining multiple conditions require us to use "|","&" for or,and operations. We must enclose them in parantheses.
-> .apply(func) can be used to execute a function for a single column where func have to be written in a way that it gets a scalar value and returns a scalar value.
    $ df[['column1','column2']].apply(lambda df: func(df['column1'],df['column2']),axis=1) this can be used for multiple columns.
    $ np.vectorize(func)(df['column1'], df['column2']) this will make the code numpy aware insted of using series it will directly use the numpy arrays so it is faster.
-> .sort_values(by=['column1','column2'],ascending=[False,True]) is used for sorting the columns and we have to pass the ascending parameter in same length as by parameter since each element corresponds to each column in by.
-> .loc[df['column'].idxmax()] is used to get the row where there is max value for column. here idxmax returns the id of the index where it is max value. this can be modified for min value as well.
-> df[num_cols].corr() this is used to get the correlation matrix for the numerical columns.
-> df['column'].value_counts() this gets the count of each category for the column.
-> df['column'].unique() used to get the unique values in the column.
-> df['column'].nunique() used to get the number of unique values in the column.
-> df['column'].replace(['key1','key2'],['value1','value2'])
    mymap = {'key1':'value2','key1':'value2'}
    df['column'].map(mymap)
    These methods are used for replace or map a value with another .These two methods does same thing with the difference in the way they take input.
-> df.duplicated() this will retrun a series which has boolean value where the next subsequent duplicate values are marked as true.
-> df['column'].between(low_range,upper_range,inclusive='right') this will get the boolean series indicating the values between the range and can use the inclusive to set both, right, left of the range is inclusive or not.
-> df.nlargest(num,'column') is used to get the rows where num number of largest values in the column. similarly we can do nsmallest.
-> df.sample(n=num) can be used to get the num number of sample. we can also get the fraction of the data set by passing frac=value.
-> Missing values are represented as NaN (not a number) in latest versions there is a pd.NaT where it indicates a missing timestamp.
    $ df['column'].isnull(),df['column'].notnull() are used to get the records which have the column as null value or not null value.
    $ df.dropna() can be used to delete the records where the there are null values. "thres" parameter can be used to conditioinaly delete records where there are the number of non null values are less than "thres" value. "subset" is a list of columns we are considering if the values in that columns are missing then the records get's dropped.
    $ df.fillna(value) can be used to fill null values with a value. we can also isolate to a column and fill na value by df['column']fillna().
    $ We should not compare null values since both missing values can be anything so they will be false we can use "is" to check conditionaly.
-> for groupby function we need a column to group and a function to aggregate. groupby gives a lazy function which can be used for aggregate.
    $ df.groupby('column').mean()['column2'], df.groupby(['column1', 'column2']).mean()['column3'] this will aggrate for single and multiple columns.
    $ The grouping columns will become the index of the dataframe.
    $ We have to specify numeric_only=True to avoid errors when aggrgating.
-> df.xs(index_value,level='index_column') this can be used to fetch the specific column and value records even if it is present in multiple indexes.
-> We can swap the levels using the df.swaplevel()
-> df.sort_index(level='column',ascending=bool_value) can be used for sorting the indexes.
-> df.agg({'mpg':['mean','median'],'acceleration':['mean','std']}) can be used to aggrate data and use different aggregation methods for different columns.
-> pd.concat([df1,df2],axis=axis_value) can be used to concat two dataframes by either of axices.
-> pd.merge(df1,df2,how='type_join',on=['column1','column2']) is used for joining two dataframes based on the type of join like left,right,outer,inner. we can alson use the left_index or right_index to sepecify that we want to join based on the index in one of the dataframe. if there are duplicate columns then we can specify argument like suffixes = ('_suffix1','_suffix2') to make sure it looks readable.
-> .str.string_func() can be used to access the string function where string_func is any func like upper, isdigit, split, strip, replace, capitalize etc...
-> pd.to_datetime(date_val) can be used to convert the string to datetime object.
    $ We can have format argument to specify which format we are using.
    $ We can pass argument parse_dates = ['column1','column2'] in the pd.read_csv directly for parsing while fetching.
    $ We can fetch date by .dt.date_fuc() in dataframes. 
-> .resample(rule='rule') can be using to group indices.
-> We can use pd.pivot(data=data,index=indeces,columns=columns,values=values) is used to restructure the table. We can also specify aggfunc to say that we want to aggregate. margins=True parameter will give the summ at the end of the column.
->

In [2]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))

In [4]:
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)

In [5]:
myindex = ['CA','NY','AZ','TX']

In [6]:
mycolumns = ['Jan','Feb','Mar']

In [7]:
df = pd.DataFrame(data=mydata,index=myindex,columns=mycolumns)

In [8]:
df

    Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [10]:
pwd

'C:\\Users\\nithishkumar\\Personal Data\\Projects\\Python projects\\python notebooks\\practice-notebooks\\ml practice'

In [11]:
ls ..\Excercises\03-Pandas

 Volume in drive C is Windows
 Volume Serial Number is 9A1E-981F

 Directory of C:\Users\nithishkumar\Personal Data\Projects\Python projects\python notebooks\practice-notebooks\Excercises\03-Pandas

02-03-2026  09:49 AM    <DIR>          .
01-03-2026  12:32 PM    <DIR>          ..
01-03-2026  12:32 PM    <DIR>          .ipynb_checkpoints
01-03-2026  12:32 PM    <DIR>          __pycache__
01-03-2026  05:48 PM           565,976 00-Series.ipynb
01-03-2026  11:13 PM           209,647 01-DataFrames.ipynb
01-03-2026  12:32 PM           194,591 02-Conditional-Filtering.ipynb
02-03-2026  09:49 AM           197,145 03-Useful-Methods.ipynb
01-03-2026  12:32 PM            64,227 04-Missing-Data.ipynb
01-03-2026  12:32 PM           219,627 05-Groupby-Operations-and-MultiIndex.ipynb
01-03-2026  12:32 PM            62,966 06-Combining-DataFrames.ipynb
01-03-2026  12:32 PM            32,972 07-Text-Methods.ipynb
01-03-2026  12:32 PM            93,392 08-Time-Methods.ipynb
01-03-2026  12:32 PM            65,234 09-Inputs-and-Outputs.ipynb
01-03-2026  12:32 PM           101,081 10-Pivot-Tables.ipynb
01-03-2026  12:32 PM            47,135 11-Pandas-Project-Exercise .ipynb
01-03-2026  12:32 PM            52,576 12-Pandas-Project-Exercise-Solution.ipynb
01-03-2026  12:32 PM                51 example.csv
01-03-2026  12:32 PM             5,022 example.xlsx
01-03-2026  12:32 PM        25,112,317 hotel_booking_data.csv
01-03-2026  12:32 PM               177 movie_scores.csv
01-03-2026  12:32 PM            17,727 mpg.csv
01-03-2026  12:32 PM             5,022 my_excel_file.xlsx
01-03-2026  12:32 PM                51 new_file.csv
01-03-2026  12:32 PM             5,021 new_workbook.xlsx
01-03-2026  12:32 PM                51 newfile.csv
01-03-2026  12:32 PM            52,132 reshaping_pivot.png
01-03-2026  12:32 PM             5,459 RetailSales_BeerWineLiquor.csv
01-03-2026  12:32 PM             1,320 Sales_Funnel_CRM.csv
01-03-2026  12:32 PM             1,330 sample_table.html
01-03-2026  12:32 PM               555 simple.html
01-03-2026  12:32 PM            18,752 tips.csv
              28 File(s)     27,131,556 bytes
               4 Dir(s)  318,610,829,312 bytes free

In [12]:
df = pd.read_csv("..\\Excercises\\03-Pandas\\tips.csv")

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [14]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [15]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [16]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [17]:
df.tail()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [18]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

In [19]:
df[['total_bill','tip']]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [20]:
df['total_bill'].add(df['tip'],fill_value=0)

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
       ...
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [21]:
df = df.set_index('Payment ID')

In [22]:
df = df.reset_index()

In [23]:
df.iloc[0]

Payment ID                     Sun2959
total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: 0, dtype: object

In [25]:
# df.loc['Sun2959']

In [26]:
df.iloc[0:4]

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994

In [28]:
# df.drop('Sun2959',axis=0).head()

In [29]:
one_row = df.iloc[0]

In [30]:
# df.append(one_row).tail()

In [31]:
df[df['tip'] < 2 ].head()

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
8,Sun6820,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377
10,Sun2546,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,566287581219
12,Sun1300,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,577040572932

In [32]:
def last_four(row):
    return str(row)[-4:]

In [33]:
df['CC Number'].apply(last_four)

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [34]:
def quality(total_bill,tip):
    if total_bill/tip > 0.05:
        return 'Generous'
    else:
        return 'Other'

In [35]:
df[['total_bill','tip']].apply(lambda df: quality(df['total_bill'],df['tip']),axis=1)

0      Generous
1      Generous
2      Generous
3      Generous
4      Generous
         ...
239    Generous
240    Generous
241    Generous
242    Generous
243    Generous
Length: 244, dtype: object

In [36]:
np.vectorize(quality)(df['total_bill'],df['tip'])

array(['Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous'], dtype='<U8')

In [37]:
# import timeit 
  
# # code snippet to be executed only once 
# setup = '''
# import numpy as np
# import pandas as pd
# df = pd.read_csv("..\Excercises\03-Pandas\tips.csv")
# def quality(total_bill,tip):
#     if tip/total_bill  > 0.25:
#         return "Generous"
#     else:
#         return "Other"
# '''
  
# # code snippet whose execution time is to be measured 
# stmt_one = ''' 
# df['Tip Quality'] = df[['total_bill','tip']].apply(lambda df: quality(df['total_bill'],df['tip']),axis=1)
# '''

# stmt_two = '''
# df['Tip Quality'] = np.vectorize(quality)(df['total_bill'], df['tip'])
# '''

# timeit.timeit(setup = setup, 
#                     stmt = stmt_one, 
#                     number = 1000) 
# timeit.timeit(setup = setup, 
#                     stmt = stmt_two, 
#                     number = 1000)

In [38]:
df.sort_values(by=['tip','size'],ascending=[False,True])

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
170,Sat1954,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236
212,Sat4590,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212
23,Sat239,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808
59,Sat8139,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595
141,Thur1025,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508
...,...,...,...,...,...,...,...,...,...,...,...
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
67,Sat3455,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267
111,Sat4801,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887
92,Fri3780,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392
236,Sat5032,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965

In [39]:
df.loc[df['total_bill'].idxmax()]

Payment ID                   Sat1954
total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
Payer Name             Gregory Clark
CC Number           5473850968388236
Name: 170, dtype: object

In [40]:
num_cols = []
for col in df.columns:
    if df[col].dtype != 'object':
        num_cols.append(col)

In [41]:
df[num_cols].corr()

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [42]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [43]:
df['sex'].nunique()

2

In [44]:
df['sex'].replace(['Female','Male'],['F','M'])

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

In [45]:
mymap = {'Female':'F','Male':'M'}
df['sex'].map(mymap)

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

In [46]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [47]:
df['total_bill'].between(10,20,inclusive='right')

0       True
1       True
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242     True
243     True
Name: total_bill, Length: 244, dtype: bool

In [49]:
df = pd.read_csv("..\\Excercises\\03-Pandas\\mpg.csv")

In [51]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [53]:
l = df.groupby('model_year')

In [64]:
# l.sum()
    # .index.names

In [66]:
year_csl = df.groupby(['model_year','cylinders']).mean(numeric_only=True)

In [69]:
year_csl.xs(4,level='cylinders')

                  mpg  displacement       weight  acceleration    origin
model_year
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [72]:
df.groupby('model_year').agg({'mpg':['mean','median'],'acceleration':['mean','std']})

                  mpg        acceleration
                 mean median         mean       std
model_year
70          17.689655  16.00    12.948276  3.330982
71          21.250000  19.00    15.142857  2.666171
72          18.714286  18.50    15.125000  2.850032
73          17.100000  16.00    14.312500  2.754222
74          22.703704  24.00    16.203704  1.688532
75          20.266667  19.50    16.050000  2.471737
76          21.573529  21.00    15.941176  2.801419
77          23.375000  21.75    15.435714  2.273391
78          24.061111  20.70    15.805556  2.129915
79          25.093103  23.90    15.813793  2.952931
80          33.696552  32.70    16.934483  2.826694
81          30.334483  31.60    16.306897  2.192509
82          31.709677  32.00    16.638710  2.484844

In [73]:
from datetime import datetime

In [75]:
mydate = datetime(2026,3,1)

In [77]:
mydate.year

2026