-> pandas dataframes is a table of columns and rows we can use to filter and perform operations.
-> it is a group of pandas series object that share the same index.
-> pd.DataFrame(data=mydata,index=myindex,columns=mycolumns) used to create a dataframe with the specified index and columns.
-> pd.read_csv() is used to read csv files we can also read many other file formats.
-> Here the columns are called features and the value or instance is called datapoint.
-> .info() is used to get the list of columns with their datatypes, memory use for the dataframe, number of missing values.
-> .columns, .index is used to get the columns and index for the dataframe.
-> .head(), .tail() is used to get the first or last five records in the dataframe which can be adjusted.
-> .describe() is used to get the common statistics like mean, median, mode, std, quartiles etc.. for each column.
-> .transpose() is used to get the transposed dataframe.
-> We can get multiple coloumns to display by giving the list of columns as a index.
-> We can drop the columns or rows using the df.drop(column_name,axis) here by default the axis is 0.
-> We can remember the axis is row or column by this analogy like we can think of shape in that the first tuple is rows and second is columns.
-> We can create a column by simply calling the column in as a index and assigning a value to it.
-> .set_index(index_name) can be used to set index of the dataframe. we can give multiple indexs.
-> .reset_index() is used to reset back to range based index and the current indexes will become into columns.
-> indexing in the dataframes can be done through below
    $ .iloc[index_val] can be used to get the row if the specific index of the dataframe is integer or not.
    $ .loc[index_str] can be used to get the row when a index of the dataframe is string value.
-> Conditions in the dataframes can be used in directly by using the conditional operators and givin the result as a index for the dataframe.
    $ Chaining multiple conditions require us to use "|","&" for or,and operations. We must enclose them in parantheses.
-> .apply(func) can be used to execute a function for a single column where func have to be written in a way that it gets a scalar value and returns a scalar value.
    $ df[['column1','column2']].apply(lambda df: func(df['column1'],df['column2']),axis=1) this can be used for multiple columns.
    $ np.vectorize(func)(df['column1'], df['column2']) this will make the code numpy aware insted of using series it will directly use the numpy arrays so it is faster.
-> .sort_values(by=['column1','column2'],ascending=[False,True]) is used for sorting the columns and we have to pass the ascending parameter in same length as by parameter since each element corresponds to each column in by.
-> .loc[df['column'].idxmax()] is used to get the row where there is max value for column. here idxmax returns the id of the index where it is max value. this can be modified for min value as well.
-> df[num_cols].corr() this is used to get the correlation matrix for the numerical columns.
-> df['column'].value_counts() this gets the count of each category for the column.
-> df['column'].unique() used to get the unique values in the column.
-> df['column'].nunique() used to get the number of unique values in the column.
-> df['column'].replace(['key1','key2'],['value1','value2'])
    mymap = {'key1':'value2','key1':'value2'}
    df['column'].map(mymap)
    These methods are used for replace or map a value with another .These two methods does same thing with the difference in the way they take input.
-> df.duplicated() this will retrun a series which has boolean value where the next subsequent duplicate values are marked as true.
-> df['column'].between(low_range,upper_range,inclusive='right') this will get the boolean series indicating the values between the range and can use the inclusive to set both, right, left of the range is inclusive or not.
-> df.nlargest(num,'column') is used to get the rows where num number of largest values in the column. similarly we can do nsmallest.
-> df.sample(n=num) can be used to get the num number of sample. we can also get the fraction of the data set by passing frac=value.
-> Missing values are represented as NaN (not a number) in latest versions there is a pd.NaT where it indicates a missing timestamp.
    $ 
->

In [2]:
import numpy as np
import pandas as pd

In [6]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))

In [7]:
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)

In [8]:
myindex = ['CA','NY','AZ','TX']

In [10]:
mycolumns = ['Jan','Feb','Mar']

In [19]:
df = pd.DataFrame(data=mydata,index=myindex,columns=mycolumns)

In [20]:
df

    Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [24]:
pwd

'C:\\Users\\nithishkumar\\Personal Data\\Projects\\Python projects\\python notebooks\\practice-notebooks\\ml practice'

In [30]:
ls ..\Excercises\03-Pandas

 Volume in drive C is Windows
 Volume Serial Number is 9A1E-981F

 Directory of C:\Users\nithishkumar\Personal Data\Projects\Python projects\python notebooks\practice-notebooks\Excercises\03-Pandas

01-03-2026  05:48 PM    <DIR>          .
01-03-2026  12:32 PM    <DIR>          ..
01-03-2026  12:32 PM    <DIR>          .ipynb_checkpoints
01-03-2026  12:32 PM    <DIR>          __pycache__
01-03-2026  05:48 PM           565,976 00-Series.ipynb
01-03-2026  12:32 PM           208,957 01-DataFrames.ipynb
01-03-2026  12:32 PM           194,591 02-Conditional-Filtering.ipynb
01-03-2026  12:32 PM           196,385 03-Useful-Methods.ipynb
01-03-2026  12:32 PM            64,227 04-Missing-Data.ipynb
01-03-2026  12:32 PM           219,627 05-Groupby-Operations-and-MultiIndex.ipynb
01-03-2026  12:32 PM            62,966 06-Combining-DataFrames.ipynb
01-03-2026  12:32 PM            32,972 07-Text-Methods.ipynb
01-03-2026  12:32 PM            93,392 08-Time-Methods.ipynb
01-03-2026  12:32 PM            65,234 09-Inputs-and-Outputs.ipynb
01-03-2026  12:32 PM           101,081 10-Pivot-Tables.ipynb
01-03-2026  12:32 PM            47,135 11-Pandas-Project-Exercise .ipynb
01-03-2026  12:32 PM            52,576 12-Pandas-Project-Exercise-Solution.ipynb
01-03-2026  12:32 PM                51 example.csv
01-03-2026  12:32 PM             5,022 example.xlsx
01-03-2026  12:32 PM        25,112,317 hotel_booking_data.csv
01-03-2026  12:32 PM               177 movie_scores.csv
01-03-2026  12:32 PM            17,727 mpg.csv
01-03-2026  12:32 PM             5,022 my_excel_file.xlsx
01-03-2026  12:32 PM                51 new_file.csv
01-03-2026  12:32 PM             5,021 new_workbook.xlsx
01-03-2026  12:32 PM                51 newfile.csv
01-03-2026  12:32 PM            52,132 reshaping_pivot.png
01-03-2026  12:32 PM             5,459 RetailSales_BeerWineLiquor.csv
01-03-2026  12:32 PM             1,320 Sales_Funnel_CRM.csv
01-03-2026  12:32 PM             1,330 sample_table.html
01-03-2026  12:32 PM               555 simple.html
01-03-2026  12:32 PM            18,752 tips.csv
              28 File(s)     27,130,106 bytes
               4 Dir(s)  318,635,274,240 bytes free

In [79]:
df = pd.read_csv("..\\Excercises\\03-Pandas\\tips.csv")

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [37]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [39]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [52]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [54]:
df.tail()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [57]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

In [64]:
df[['total_bill','tip']]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [68]:
df['total_bill'].add(df['tip'],fill_value=0)

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
       ...
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [95]:
df = df.set_index('Payment ID')

In [86]:
df = df.reset_index()

In [93]:
df.iloc[0]

Payment ID                     Sun2959
Payer Name          Christy Cunningham
total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
CC Number             3560325168603410
Name: 0, dtype: object

In [100]:
df.loc['Sun2959']

Payer Name          Christy Cunningham
total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [102]:
df.iloc[0:4]

,Payer Name,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number
Payment ID,,,,,,,,,,
Sun2959,Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410
Sun4608,Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230
Sun4458,Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322
Sun5260,Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994

In [103]:
df.drop('Sun2959',axis=0).head()

,Payer Name,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number
Payment ID,,,,,,,,,,
Sun4608,Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230
Sun4458,Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322
Sun5260,Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994
Sun2251,Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221
Sun9679,Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882

In [104]:
one_row = df.iloc[0]

In [108]:
# df.append(one_row).tail()

In [112]:
df[df['tip'] < 2 ].head()

,Payer Name,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number
Payment ID,,,,,,,,,,
Sun2959,Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410
Sun4608,Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230
Sun6820,Joseph Mcdonald,15.04,1.96,Male,No,Sun,Dinner,2,7.52,3522866365840377
Sun2546,William Riley,10.27,1.71,Male,No,Sun,Dinner,2,5.14,566287581219
Sun1300,Chad Harrington,15.42,1.57,Male,No,Sun,Dinner,2,7.71,577040572932

In [113]:
def last_four(row):
    return str(row)[-4:]

In [115]:
df['CC Number'].apply(last_four)

Payment ID
Sun2959    3410
Sun4608    9230
Sun4458    1322
Sun5260    5994
Sun2251    7221
           ...
Sat2657    2842
Sat1766    5404
Sat3880    7196
Sat17      0950
Thur672    8139
Name: CC Number, Length: 244, dtype: object

In [136]:
def quality(total_bill,tip):
    if total_bill/tip > 0.05:
        return 'Generous'
    else:
        return 'Other'

In [137]:
df[['total_bill','tip']].apply(lambda df: quality(df['total_bill'],df['tip']),axis=1)

Payment ID
Sun2959    Generous
Sun4608    Generous
Sun4458    Generous
Sun5260    Generous
Sun2251    Generous
             ...
Sat2657    Generous
Sat1766    Generous
Sat3880    Generous
Sat17      Generous
Thur672    Generous
Length: 244, dtype: object

In [138]:
np.vectorize(quality)(df['total_bill'],df['tip'])

array(['Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous', 'Generous',
       'Generous', 'Generous', 'Generous', 'Generous'], dtype='<U8')

In [129]:
# import timeit 
  
# # code snippet to be executed only once 
# setup = '''
# import numpy as np
# import pandas as pd
# df = pd.read_csv("..\Excercises\03-Pandas\tips.csv")
# def quality(total_bill,tip):
#     if tip/total_bill  > 0.25:
#         return "Generous"
#     else:
#         return "Other"
# '''
  
# # code snippet whose execution time is to be measured 
# stmt_one = ''' 
# df['Tip Quality'] = df[['total_bill','tip']].apply(lambda df: quality(df['total_bill'],df['tip']),axis=1)
# '''

# stmt_two = '''
# df['Tip Quality'] = np.vectorize(quality)(df['total_bill'], df['tip'])
# '''

# timeit.timeit(setup = setup, 
#                     stmt = stmt_one, 
#                     number = 1000) 
# timeit.timeit(setup = setup, 
#                     stmt = stmt_two, 
#                     number = 1000)

In [144]:
df.sort_values(by=['tip','size'],ascending=[False,True])

,Payer Name,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number
Payment ID,,,,,,,,,,
Sat1954,Gregory Clark,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,5473850968388236
Sat4590,Alex Williamson,48.33,9.00,Male,No,Sat,Dinner,4,12.08,676218815212
Sat239,Lance Peterson,39.42,7.58,Male,No,Sat,Dinner,4,9.86,3542584061609808
Sat8139,Brian Ortiz,48.27,6.73,Male,No,Sat,Dinner,4,12.07,6596453823950595
Thur1025,Steven Carlson,34.30,6.70,Male,No,Thur,Lunch,6,5.72,3526515703718508
...,...,...,...,...,...,...,...,...,...,...
Sun2959,Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410
Sat3455,Tiffany Brock,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,4359488526995267
Sat4801,Terri Jones,7.25,1.00,Female,No,Sat,Dinner,1,7.25,3559221007826887
Fri3780,Leah Ramirez,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,3508911676966392
Sat5032,Matthew Myers,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,3543676378973965

In [152]:
df.loc[df['total_bill'].idxmax()]

Payer Name             Gregory Clark
total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
CC Number           5473850968388236
Name: Sat1954, dtype: object

In [154]:
num_cols = []
for col in df.columns:
    if df[col].dtype != 'object':
        num_cols.append(col)

In [156]:
df[num_cols].corr()

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [160]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [161]:
df['sex'].nunique()

2

In [163]:
df['sex'].replace(['Female','Male'],['F','M'])

Payment ID
Sun2959    F
Sun4608    M
Sun4458    M
Sun5260    M
Sun2251    F
          ..
Sat2657    M
Sat1766    F
Sat3880    M
Sat17      M
Thur672    F
Name: sex, Length: 244, dtype: object

In [165]:
mymap = {'Female':'F','Male':'M'}
df['sex'].map(mymap)

Payment ID
Sun2959    F
Sun4608    M
Sun4458    M
Sun5260    M
Sun2251    F
          ..
Sat2657    M
Sat1766    F
Sat3880    M
Sat17      M
Thur672    F
Name: sex, Length: 244, dtype: object

In [167]:
df.duplicated()

Payment ID
Sun2959    False
Sun4608    False
Sun4458    False
Sun5260    False
Sun2251    False
           ...
Sat2657    False
Sat1766    False
Sat3880    False
Sat17      False
Thur672    False
Length: 244, dtype: bool

In [170]:
df['total_bill'].between(10,20,inclusive='right')

Payment ID
Sun2959     True
Sun4608     True
Sun4458    False
Sun5260    False
Sun2251    False
           ...
Sat2657    False
Sat1766    False
Sat3880    False
Sat17       True
Thur672     True
Name: total_bill, Length: 244, dtype: bool